[package]
name = "nukemaster619/test-hooks"
description = "A collection of lua react hooks."
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["Packages"]

[dependencies]
react = "jsdotlua/react@17.1.0"